#ifndef EASY_GETTEXT_VERSION

#define EASY_GETTEXT_VERSION_MAJOR 0
#define EASY_GETTEXT_VERSION_MINOR 1
#define EASY_GETTEXT_VERSION_REV 1

#define EASY_GETTEXT_str(a) #a
#define EASY_GETTEXT_xstr(a) EASY_GETTEXT_str(a)

#ifdef UNICODE_SUPPORT
#define EASY_GETTEXT_VERSION EASY_GETTEXT_xstr(EASY_GETTEXT_VERSION_MAJOR) "." EASY_GETTEXT_xstr(EASY_GETTEXT_VERSION_MINOR) "." EASY_GETTEXT_xstr(EASY_GETTEXT_VERSION_REV) "u"
#else
#define EASY_GETTEXT_VERSION EASY_GETTEXT_xstr(EASY_GETTEXT_VERSION_MAJOR) "." EASY_GETTEXT_xstr(EASY_GETTEXT_VERSION_MINOR) "." EASY_GETTEXT_xstr(EASY_GETTEXT_VERSION_REV)
#endif

#endif